### ISSUE TITLE
Form starts validating before a user visits a field

### ISSUE THREAD

**Issue by khwilo** [khwilo/registration-form-validation#1]
## Description

The form fields are marked as invalid by displaying a red outline when a user visits the site for the first time before focusing/visiting the input field. Currently, I have commented in the code to style the input field outline when it is invalid in the CSS file.

```CSS
/* input:not(:focus):invalid {
  outline: 2px solid var(--clr-error);
  border: none;
} */
```

To replicate this behavior, comment out the above code in the CSS file.
## Demo

The form starts as depicted in the following image:

![error-validation-start](https://user-images.githubusercontent.com/5740429/74564841-fe5ae780-4f80-11ea-8243-329bf1a852d6.png)
